Introdução
Começaremos com uma visão geral de como funcionam os modelos de aprendizado de máquina e como eles são usados. Isso pode parecer básico se você já fez modelagem estatística ou aprendizado de máquina antes. Não se preocupe, em breve passaremos a construir modelos poderosos.
Este curso terá você construindo modelos à medida que você segue o seguinte cenário:
Seu primo ganhou milhões de dólares especulando em imóveis. Ele ofereceu-se para se tornar seu parceiro de negócios por causa de seu interesse em ciência de dados. Ele fornecerá o dinheiro, e você fornecerá modelos que prevejam quanto valem várias casas.
Você pergunta ao seu primo como ele previu os valores imobiliários no passado, e ele diz que é apenas intuição. Mas mais perguntas revelam que ele identificou padrões de preços das casas que ele viu no passado, e ele usa esses padrões para fazer previsões para novas casas que está considerando.
A aprendizagem de máquina funciona da mesma forma. Começaremos com um modelo chamado Árvore de Decisão. Existem modelos mais sofisticados que dão previsões mais precisas. Mas as árvores de decisão são fáceis de entender e são o bloco básico para alguns dos melhores modelos em ciência de dados.
Para simplificar, começaremos com a árvore de decisão mais simples possível.

Isso divide as casas em apenas duas categorias. O preço previsto para qualquer casa em consideração é o preço médio histórico das casas na mesma categoria.
Usamos dados para decidir como dividir as casas em dois grupos e, em seguida, determinar o preço previsto em cada grupo. Essa etapa de capturar padrões a partir de dados é chamada de ajuste ou treinamento do modelo. Os dados usados ​​para ajustar o modelo são chamados de dados de treinamento.
Os detalhes de como o modelo é ajustado (por exemplo, como dividir os dados) são complexos o suficiente para que possamos deixá-los para mais tarde. Depois que o modelo for ajustado, você poderá aplicá-lo a novos dados para prever os preços de casas adicionais.

Melhorando a Árvore de Decisão
Qual das duas árvores de decisão a seguir é mais provável de resultar do ajuste dos dados de treinamento imobiliário?
A árvore de decisão da esquerda (Árvore de Decisão 1) provavelmente faz mais sentido, porque captura a realidade de que casas com mais quartos tendem a ser vendidas a preços mais altos do que casas com menos quartos. A maior limitação desse modelo é que ele não captura a maioria dos fatores que afetam o preço da casa, como número de banheiros, tamanho do lote, localização, etc.
Você pode capturar mais fatores usando uma árvore que tem mais "divisões". Estas são chamadas de árvores "mais profundas". Uma árvore de decisão que também considera o tamanho total do lote de cada casa pode parecer assim:
Você prevê o preço de qualquer casa percorrendo a árvore de decisão, sempre escolhendo o caminho correspondente às características daquela casa. O preço previsto para a casa está na parte inferior da árvore. O ponto na parte inferior onde fazemos uma previsão é chamado de folha.
As divisões e valores nas folhas serão determinados pelos dados, então é hora de você dar uma olhada nos dados com os quais estará trabalhando.




Usando o Pandas para se familiarizar com os dados
O primeiro passo em qualquer projeto de machine learning é se familiarizar com os dados. Você usará a biblioteca Pandas para isso. O Pandas é a principal ferramenta que cientistas de dados usam para explorar e manipular dados. A maioria das pessoas abrevia pandas em seu código como pd. Fazemos isso com o comando:

In [ ]:
import pandas as pd

A parte mais importante da biblioteca Pandas é o DataFrame. Um DataFrame contém o tipo de dados que você pode pensar como uma tabela. Isso é semelhante a uma planilha no Excel ou a uma tabela em um banco de dados SQL.

O Pandas possui métodos poderosos para a maioria das coisas que você deseja fazer com esse tipo de dados.

Como exemplo, vamos olhar os dados sobre os preços das casas em Melbourne, Austrália. Nos exercícios práticos, você aplicará os mesmos processos a um novo conjunto de dados, que tem preços de casas em Iowa.

Os dados de exemplo (Melbourne) estão no caminho do arquivo ../input/melbourne-housing-snapshot/melb_data.csv.

Carregamos e exploramos os dados com os seguintes comandos:

In [9]:
# save filepath to variable for easier access
melbourne_file_path = '/kaggle/input/melb-data/melb_data.csv'
# read the data and store data in DataFrame titled melbourne_data
melbourne_data = pd.read_csv(melbourne_file_path)

Interpretando a descrição dos dados
Os resultados mostram 8 números para cada coluna no conjunto de dados original. O primeiro número, a contagem, mostra quantas linhas têm valores não faltantes.

Os valores faltantes surgem por muitas razões. Por exemplo, o tamanho do segundo quarto não seria coletado ao pesquisar uma casa de 1 quarto. Voltaremos ao tópico de dados faltantes posteriormente.

O segundo valor é a média, que é a média aritmética. Abaixo disso, o std é o desvio padrão, que mede como os valores estão numericamente espalhados.

Para interpretar os valores min, 25%, 50%, 75% e max, imagine que cada coluna seja ordenada do valor mais baixo para o mais alto. O primeiro (menor) valor é o min. Se você avançar um quarto da lista, encontrará um número que é maior do que 25% dos valores e menor do que 75% dos valores. Esse é o valor de 25% (pronunciado "percentil 25"). Os percentis 50 e 75 são definidos analogamente, e o valor máximo é o maior número.

In [11]:
# print a summary of the data in Melbourne data
pd.set_option('display.max_columns', None)
melbourne_data.describe()

,Unnamed: 0,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,18396.000000,18396.000000,1.839600e+04,18395.000000,18395.000000,14927.000000,14925.000000,14820.000000,13603.000000,7762.000000,8958.000000,15064.000000,15064.000000,18395.000000
mean,11826.787073,2.935040,1.056697e+06,10.389986,3107.140147,2.913043,1.538492,1.615520,558.116371,151.220219,1965.879996,-37.809849,144.996338,7517.975265
std,6800.710448,0.958202,6.419217e+05,6.009050,95.000995,0.964641,0.689311,0.955916,3987.326586,519.188596,37.013261,0.081152,0.106375,4488.416599
min,1.000000,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,5936.750000,2.000000,6.330000e+05,6.300000,3046.000000,2.000000,1.000000,1.000000,176.500000,93.000000,1950.000000,-37.858100,144.931193,4294.000000
50%,11820.500000,3.000000,8.800000e+05,9.700000,3085.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.803625,145.000920,6567.000000
75%,17734.250000,3.000000,1.302000e+06,13.300000,3149.000000,3.000000,2.000000,2.000000,651.000000,174.000000,2000.000000,-37.756270,145.060000,10331.000000
max,23546.000000,12.000000,9.000000e+06,48.100000,3978.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [12]:
# Visualizando as colunas
melbourne_data.columns

Index(['Unnamed: 0', 'Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method',
       'SellerG', 'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea',
       'Lattitude', 'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

Selecionando dados para modelagem

Seu conjunto de dados tinha muitas variáveis para entender ou até mesmo imprimir com clareza. Como você pode reduzir essa quantidade avassaladora de dados para algo que possa entender?

Começaremos selecionando algumas variáveis usando nossa intuição. Cursos posteriores mostrarão técnicas estatísticas para priorizar variáveis automaticamente.

Para escolher as variáveis/colunas, precisaremos ver uma lista de todas as colunas no conjunto de dados. Isso é feito com a propriedade columns do DataFrame (a última linha de código abaixo).

In [13]:
# O conjunto de dados de Melbourne tem alguns valores ausentes (algumas casas para as quais algumas variáveis não foram registradas).
# Aprenderemos a lidar com valores ausentes em um tutorial posterior. 
# Seus dados de Iowa não têm valores ausentes nas colunas que você usa.
# Então, por enquanto, vamos escolher a opção mais simples e eliminar as casas dos nossos dados.
# Mas não se preocupe com isso por enquanto, o código é:

# dropna elimina valores ausentes (pense em "na" como "não disponível")
melbourne_data = melbourne_data.dropna(axis=0)

Existem muitas maneiras de selecionar um subconjunto de seus dados. O curso de Pandas aborda isso com mais profundidade, mas nos concentraremos em duas abordagens por enquanto.

Notação de ponto, que usamos para selecionar o "target de predição"
Selecionando com uma lista de colunas, que usamos para selecionar as "features"

Selecionando o alvo de predição
Você pode extrair uma variável com a notação de ponto. Essa única coluna é armazenada em uma Series, que é amplamente semelhante a um DataFrame com apenas uma única coluna de dados.

Usaremos a notação de ponto para selecionar a coluna que queremos prever, que é chamada de alvo de previsão. Por convenção, o alvo de previsão é chamado de y. Portanto, o código que precisamos para salvar os preços das casas nos dados de Melbourne é:

In [14]:
# Alvo da previsão - chamado de y
y = melbourne_data.Price

In [15]:
y

1        1035000.0
2        1465000.0
4        1600000.0
6        1876000.0
7        1636000.0
           ...
15388     601000.0
15389    1050000.0
15390     385000.0
15392     560000.0
15395    2450000.0
Name: Price, Length: 6196, dtype: float64

Escolhendo "Recursos"
As colunas que são inseridas no nosso modelo (e posteriormente usadas para fazer previsões) são chamadas de "recursos". No nosso caso, essas seriam as colunas usadas para determinar o preço da casa. Às vezes, você usará todas as colunas, exceto a variável alvo, como recursos. Outras vezes, será melhor usar menos recursos.

Por enquanto, construiremos um modelo com apenas alguns recursos. Mais tarde, você verá como iterar e comparar modelos construídos com diferentes recursos.

Selecionamos vários recursos fornecendo uma lista de nomes de colunas entre colchetes. Cada item nessa lista deve ser uma string (entre aspas).

Aqui está um exemplo:

In [17]:
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

Por convenção, os dados são chamados de X

In [19]:
X = melbourne_data[melbourne_features]

Vamos rapidamente revisar os dados que usaremos para prever preços de casas usando o método describe e o método head, que mostra as primeiras linhas.

In [20]:
X.describe()

             Rooms     Bathroom      Landsize    Lattitude   Longtitude
count  6196.000000  6196.000000   6196.000000  6196.000000  6196.000000
mean      2.931407     1.576340    471.006940   -37.807904   144.990201
std       0.971079     0.711362    897.449881     0.075850     0.099165
min       1.000000     1.000000      0.000000   -38.164920   144.542370
25%       2.000000     1.000000    152.000000   -37.855438   144.926198
50%       3.000000     1.000000    373.000000   -37.802250   144.995800
75%       4.000000     2.000000    628.000000   -37.758200   145.052700
max       8.000000     8.000000  37000.000000   -37.457090   145.526350

In [21]:
X.head()

   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954

Verificar visualmente os dados com esses comandos é uma parte importante do trabalho de um cientista de dados. Com frequência, você encontrará surpresas no conjunto de dados que merecem uma inspeção mais detalhada.

Você usará a biblioteca scikit-learn para criar seus modelos. Ao codificar, essa biblioteca é escrita como sklearn, como você verá no código de exemplo. O scikit-learn é facilmente a biblioteca mais popular para modelar os tipos de dados normalmente armazenados em DataFrames.

Os passos para construir e usar um modelo são:

Definir: Que tipo de modelo será? Uma árvore de decisão? Algum outro tipo de modelo? Alguns outros parâmetros do tipo de modelo também são especificados.
Fit: Capturar padrões a partir dos dados fornecidos. Este é o coração da modelagem.
Prever: Exatamente o que parece
Avaliar: Determinar a precisão das previsões do modelo.

Aqui está um exemplo de definição de um modelo de árvore de decisão com o scikit-learn e ajustando-o com as características e a variável de destino.

In [23]:
from sklearn.tree import DecisionTreeRegressor

# Defina o modelo. Especifique um número para random_state para garantir os mesmos resultados em cada execução
melbourne_model = DecisionTreeRegressor(random_state=1)

# O modelo é ajustado aos dados de treinamento usando a função fit(). Neste exemplo, os dados de treinamento são X e y
melbourne_model.fit(X, y)

DecisionTreeRegressor(random_state=1)

In [24]:
DecisionTreeRegressor(random_state=1)

DecisionTreeRegressor(random_state=1)

Muitos modelos de machine learning permitem algum nível de aleatoriedade no treinamento do modelo. Especificar um número para random_state garante que você obtenha os mesmos resultados em cada execução. Isso é considerado uma boa prática. Você pode usar qualquer número, e a qualidade do modelo não dependerá significativamente do valor exato que você escolher.

Agora temos um modelo ajustado que podemos usar para fazer previsões.

Na prática, você vai querer fazer previsões para novas casas que chegam ao mercado, em vez das casas para as quais já temos preços. Mas faremos previsões para as primeiras linhas dos dados de treinamento para ver como funciona a função predict.

In [25]:
print("Fazendo previsões para as seguintes 5 casas:")
print(X.head())
print("As predições são:")
print(melbourne_model.predict(X.head()))

Fazendo previsões para as seguintes 5 casas:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954
As predições são:
[1035000. 1465000. 1600000. 1876000. 1636000.]

In [27]:
print("Fazendo previsões para as seguintes 50 casas:")
print(X.head(50))
print("As predições são:")
print(melbourne_model.predict(X.head(50)))

Fazendo previsões para as seguintes 50 casas:
     Rooms  Bathroom  Landsize  Lattitude  Longtitude
1        2       1.0     156.0   -37.8079    144.9934
2        3       2.0     134.0   -37.8093    144.9944
4        4       1.0     120.0   -37.8072    144.9941
6        3       2.0     245.0   -37.8024    144.9993
7        2       1.0     256.0   -37.8060    144.9954
11       2       1.0     220.0   -37.8010    144.9989
16       3       2.0     214.0   -37.8085    144.9964
17       2       2.0       0.0   -37.8078    144.9965
22       2       1.0     238.0   -37.8090    144.9976
23       3       2.0     113.0   -37.8056    144.9930
25       3       1.0     138.0   -37.8021    144.9965
27       2       1.0     150.0   -37.8011    145.0004
28       4       2.0     780.0   -37.8073    144.9952
31       2       1.0       0.0   -37.8015    144.9972
32       2       2.0     124.0   -37.8079    144.9977
33       2       1.0     147.0   -37.8080    144.9940
37       3       3.0     166.0   -37.8017    145.0001
39       2       2.0      98.0   -37.8005    144.9952
44       3       1.0     168.0   -37.8007    144.9958
45       1       1.0       0.0   -37.8055    144.9961
46       2       1.0     162.0   -37.8016    144.9956
47       3       2.0     120.0   -37.8022    144.9954
48       2       1.0     182.0   -37.8021    144.9976
50       2       1.0     172.0   -37.8086    144.9946
52       3       2.0     303.0   -37.7180    144.8780
53       3       2.0       0.0   -37.7203    144.8755
54       3       2.0       0.0   -37.7203    144.8755
55       2       1.0     272.0   -37.7294    144.8880
56       3       2.0     239.0   -37.7218    144.8837
57       3       1.0     290.0   -37.7273    144.8744
58       2       1.0     168.0   -37.7215    144.8864
66       6       3.0     976.0   -37.7239    144.8735
67       2       1.0     110.0   -37.7216    144.8710
68       2       1.0     141.0   -37.7298    144.8883
70       2       1.0     120.0   -37.7234    144.8792
71       3       1.0    1063.0   -37.7249    144.8728
73       3       1.0       0.0   -37.7217    144.8783
75       3       1.0     265.0   -37.7302    144.8855
83       3       2.0     165.0   -37.7270    144.8870
85       3       1.0     971.0   -37.7186    144.8760
88       2       1.0     612.0   -37.7187    144.8765
89       3       2.0     612.0   -37.7173    144.8796
91       4       3.0     531.0   -37.7263    144.8679
93       3       3.0     555.0   -37.7285    144.8694
94       3       2.0     422.0   -37.7164    144.8792
97       3       2.0     161.0   -37.7231    144.8802
98       3       2.0     293.0   -37.7200    144.8776
99       3       1.0     579.0   -37.7226    144.8733
113      4       2.0     628.0   -37.7256    144.8739
117      2       1.0     120.0   -37.8459    144.9555
As predições são:
[1035000. 1465000. 1600000. 1876000. 1636000. 1097000. 1350000.  750000.
 1310000. 1200000. 1176500.  890000. 1330000.  500000. 1100000. 1315000.
 1447500. 1135000. 1290000.  470000. 1180000. 1195000. 1012500. 1030000.
  840000.  750000.  750000.  603000.  700000.  600000.  500000.  725000.
  450000.  515000.  530000.  895000.  805000.  752000.  700000.  830000.
  675000. 1042000.  773000.  810000.  715000.  540000.  825000.  685000.
  900000. 1275000.]